### ISSUE TITLE
Title for this workshop

### ISSUE THREAD

**Issue by ZoinerTejada** [solliancenet/MCW-Azure-Synapse-Analytics#3]
Please use this issue to suggest titles for the workshop, as what we have **Azure Synapse Analytics** is simply a placeholder title.

**Comment by ZoinerTejada** [comment]
Modern Analytics with Azure Synapse Analytics

End-to-end analytic solutions with Azure Synapse Analytics

**Comment by nderhem** [comment]
Azure Synapse Analytics End-to-End solution ?

**Comment by DawnmarieDesJardins** [comment]
Per Sanjay - let's go with:
Azure Synapse Analytics end-to-end solution

**Comment by ZoinerTejada** [comment]
Updated title to **Azure Synapse Analytics end-to-end solution**
