### ISSUE TITLE
Use of Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by shashankkhedikar** [solliancenet/MCW-Azure-Synapse-Analytics#4]
on Landing page I see use of 'Azure SQL Data Warehouse' this is not aligned with branding: Azure Synapse Analytics (formerly known as Azure SQL Data Warehouse)

**Comment by ZoinerTejada** [comment]
Your comment refers to the root readme.md. This file was not updated with any content, it was still the template. 

It has has been updated to reflect the whiteboard design session.
