### ISSUE TITLE
Hot path diagram needs review

### ISSUE THREAD

**Issue by shashankkhedikar** [solliancenet/MCW-Azure-Synapse-Analytics#5]
SQL on-demand is more off a Query as a Service not for Hot Path. This needs to be reviewed from product engineering. For hot-path refer Delta Lake or streaming in Apache Spark.   

https://github.com/solliancenet/MCW-Azure-Synapse-Analytics/blob/master/Whiteboard%20design%20session/media/preferred-solution-streaming.png

**Comment by ZoinerTejada** [comment]
This diagram has been updated to address your concern.
