### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by shashankkhedikar** [solliancenet/MCW-Azure-Synapse-Analytics#6]
Below statement is wrong as ADLS gen 2 is a part of Azure Synapse Analytics
o	The important take away from this architecture is that all of the components shown except Azure Data Lake Store gen 2 are managed within Azure Synapse
This diagram is little confusing too Azure Synapse Analytics text is in Ingest and Prepare box only. However in Synapse we can do all. 
https://raw.githubusercontent.com/solliancenet/MCW-Azure-Synapse-Analytics/master/Whiteboard%20design%20session/media/preferred-solution.png

**Comment by ZoinerTejada** [comment]
That statement has been removed and the diagram has had several revisions to improve the clarity. Note the Azure Synapse Analytics label applies to the rectangle that goes across all phases. Additional clarity has been provided in the updated nomenclature. These updates were requested by Kaiser.
