### ISSUE TITLE
Use SQL On-demand and/or Query as a Service  

### ISSUE THREAD

**Issue by shashankkhedikar** [solliancenet/MCW-Azure-Synapse-Analytics#7]
1. Before building transformation pipelines or loading it into the data warehouse, 
   how can WWI quickly explore the raw ingested data to understand its contents?
ANS : Using Azure Synapse Analytics Studio, for any parquet files stored in ADLS,
      they can right click on a parquet file to query as SQL or as DataFrame in a notebook.

**Comment by ZoinerTejada** [comment]
I'm not sure I understand your comment. This questions was geared more towards the experience rather than what was used to execute the query/notebook. The latter is explained in several places already. If you have further comment, please clarify and I will re-open this issue to address it.
